### DISCUSSION TITLE
Updating clear out channels and sources?

### DISCUSSION THREAD

**Discussion by techno-mike-git** [chrisbenincasa/tunarr#1012] [Questions & Help] [answered]
Hi!
Does updating clear out my channels and sources? I have watchtower that recently update tunarr and it seems to clear out everything. Is there a way to safely update?

**Comment by chrisbenincasa** [comment]
Can you paste in your docker command / compose file?

**Reply by techno-mike-git** [reply]
Oh man it clear out my channels again. I might have to turn off watchtower. I believe if I do a recreate with docker it does the same:
```
services:
  tunarr:
    image: chrisbenincasa/tunarr:latest-vaapi
    container_name: tunarr
    group_add:
      - '107'
    ports:
      - 8088:8000
    environment:
      - LOG_LEVEL=INFO
      - TZ=America/Los_Angeles
      - TUNARR_DATABASE_PATH=/docker/tunarr
    volumes:
      - /docker/tunarr:/config/tunarr
    networks:
      - servarr_default
    devices:
      - /dev/dri:/dev/dri

networks:
  servarr_default:
    external: true
```
