### DISCUSSION TITLE
Losing settings

### DISCUSSION THREAD

**Discussion by EmilMoe** [chrisbenincasa/tunarr#844] [General]
Every time the container is recreated I lose all settings. I suppose there's a folder I haven't mapped?

Edit: This is for docker-compose of course.

**Comment by chrisbenincasa** [comment]
Ah sorry about that,, looks like the docs missed that for the compose example. But yes, you need to a volume bind mount. Data in container is by default saved to /config/tunarr. I've just updated the docs to include that in the docker-compose example

**Comment by AnterosOberon** [comment]
For the novice where is this setting,. I have built this container out and set this application up 40+ times and every few days I come back and everything is gone. Now I just make one channel and wait to see how long before its wiped out.

**Reply by EmilMoe** [reply]
```
version: '3.8'
services:
  tunarr:
    image: chrisbenincasa/tunarr:edge
    # Uncomment along with runtime below to enable HW accel
    # image: chrisbenincasa/tunarr:edge-nvidia
    container_name: tunarr
    ports:
      - 8088:8000
    # Uncomment if using the Nvidia container
    # runtime: nvidia
    environment:
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
    volumes:
      - ./config:/config/tunarr
      # The host path is relative to the location of the compose file
      # This can also use an absolute path.
      #
      # Uncomment if migrating from dizquetv. Chnage the host path
      # to the location of your dizquetv "database"
      #- ./dizquetv:/.dizquetv
```
