### ISSUE TITLE
Docker Compose Not Working

### ISSUE THREAD

**Issue by naby-dev** [chrisbenincasa/tunarr#1088]
Hello! 
I'm trying to run this with docker compose using this: `docker-compose --env-file .env -f applications/tunarr/docker-compose.yml -p tunarr up -d`
```
networks:
  mediarr-network:
    external: true

services:
  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/tunarr:/tunarr
    restart: unless-stopped
    ports:
      - 8088:8000
    networks: 
      - mediarr-network
```

And I keep getting this:
```
Starting tunarr ... error

ERROR: for tunarr  Cannot start service tunarr: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/tunarr/tunarr-linux-x64": stat /tunarr/tunarr-linux-x64: no such file or directory: unknown

ERROR: for tunarr  Cannot start service tunarr: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/tunarr/tunarr-linux-x64": stat /tunarr/tunarr-linux-x64: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

Any help?
Thanks in advance

**Comment by chrisbenincasa** [comment]
Hey sorry for the trouble. We're in the midst of setting up a new runtime for Tunarr. You can use the 0.18.7 image for now which should work as expected.

**Comment by gottsman** [comment]
I can confirm that the latest version suddenly doesn't start. I don't see anything in the logs. Revering back to **chrisbenincasa/tunarr:0.18.7-nvidia** works fine for me.

**Comment by naby-dev** [comment]
> ~Hey sorry for the trouble. We're in the midst of setting up a new runtime for Tunarr. You can use the 0.18.7 image for now which should work as expected.~
> 
> Actually I think the issue is in your config. you are binding to `/tunarr` within the container, which is where the executable lives (and thus overwriting it). You want to bind your volume to `/config/tunarr`. See https://tunarr.com/getting-started/run/

I did initially try /confi/tunarr with no luck but it is noted. Will give it another try when I get the chance 

Thank you

**Comment by chrisbenincasa** [comment]
I've pushed a new image, but it really shouldn't contain anything different. I'm able to run the compose from the docs against it without issue. 

I need to update the docs, but as I mentioned there's a new set of images for older CPUs that don't support certain optimizations that the new Tunarr binaries use. If you are still having problems, you can try these new images. The tags are similar but with the word "baseline" added. Examples: "latest-baseline" or "latest-baseline-nvidia"

**Comment by chrisbenincasa** [comment]
Are you still having an issue here? I believe I have fixed this.

**Comment by gottsman** [comment]
I tried against **chrisbenincasa/tunarr:0.18.11-nvidia** and it seemed to work fine.

**Comment by naby-dev** [comment]
Apologies, things got busy. I'm gonna try and give it a shot again asap.

I see that you say I need to do things slightly different if I'm running pre-2013 cpus.
I'm running a i5 4670k which I believe released in June '13.
I also have no graphics card too.  Should I be using baseline tags?

**Comment by chrisbenincasa** [comment]
Should've updated, the baseline and old cpu concerns are no longer relevant since I reverted the runtime changes due to other issues and concerns.

**Comment by naby-dev** [comment]
Just tried it and seems to be working.
Thanks for the help! 
I'll drop my compose below for others in the future:
```
networks:
  mediarr-network:
    external: true

services:
  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA}/tunarr/config/tunarr:/config/tunarr
    restart: unless-stopped
    ports:
      - 8088:8000
    networks: 
      - mediarr-network
```
